Repository Progress-House/ofitoo-api, pull requests merged in 2024-04, with the labels that each got.

#42 41-feat-readmemd-building-project-and-basic-information
  README.md
  microservice-architecture.png
Labels: doc/, feature

#43 refactored docker-compose name to product-db for better clarity
  README.md
  scripts/product-db.yml
Labels: refactor

#44 improving info how to build project
  README.md
Labels: doc/

#12 5-gh-action-protect-branch-develop-against-the-project-not-being-built
  .github/workflows/build-dev.yml
Labels: devops issue
